### ISSUE TITLE
Crash on API 27

### ISSUE THREAD

**Issue by ravindu1024** [Siclo-Mobile/EZPhotoPicker#23]
App crashes when I try to launch the gallery on API 27. Here's the trace:

``Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.os.Parcel.readException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1888)
        at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
        at android.app.Activity.setRequestedOrientation(Activity.java:5739)
        at siclo.com.ezphotopicker.ui.PhotoIntentHelperActivity.onCreate(PhotoIntentHelperActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
``

**Comment by mustafakayya** [comment]
I have same problem.

**Comment by khanhsiclo** [comment]
The issue has been fixed on version 1.0.10
